appsSubdomain: {{ code_red_breach_challenge_argo_customize_apps_subdomain }}
namespace: leaderboard

ctfd:
  cidr: {{ code_red_breach_challenge_argo_customize_cidr }}
  userCreation:
    enabled: true
    image:
      repository: registry.redhat.io/openshift4/ose-tools-rhel9
      pullPolicy: IfNotPresent
      tag: latest
    userCount: {{ code_red_breach_challenge_argo_customize_num_users }}
    userPrefix: {{ code_red_breach_challenge_argo_customize_gitea_user_name_base }}
    userDefaultPassword: {{ code_red_breach_challenge_argo_customize_gitea_user_password }}
  replicaCount: 1
  image:
    repository: ghcr.io/ctfd/ctfd
    pullPolicy: IfNotPresent
    tag: latest
  env:
    open:
      # Required if more than 1 worker (randomly generate)
      SECRET_KEY: "ZYqWHRHK4bGYc273ylwPae1"
      # Amount of CTFd workers
      WORKERS: 1
      # If behing ingress proxy or nginx:
      REVERSE_PROXY: True
  probes:
    liveness:
      initialDelaySeconds: 25
      periodSeconds: 5
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 5
    readiness:
      initialDelaySeconds: 20
      periodSeconds: 5
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 5
  pvc:
    volume_capacity: 5Gi

redis:
  image:
    repository: registry.redhat.io/rhel9/redis-7
    pullPolicy: IfNotPresent
    tag: 9.5
  nameOverride: redis
  memory_limit: 512Mi
  redis_password: oQx2b2x4B5L
  pvc:
    volume_capacity: 1Gi

mariadb:
  image:
    repository: registry.redhat.io/rhel9/mariadb-1011
    pullPolicy: IfNotPresent
    tag: 9.5
  nameOverride: mariadb
  memory_limit: 512Mi
  mysql_database: ctfddb
  mysql_password: 5viD1QBxOmgYehAaWrANgg5
  mysql_root_password: 4mteyiyyuk7591gosVp70a1
  mysql_user: dbadmin
  pvc:
    volume_capacity: 1Gi
